### ISSUE TITLE
Feature request .ics output

### ISSUE THREAD

**Issue by samuk** [dandelion-collective/dandelion#33]
Would you be interested in adding a .ics feed per organisation? Events could be represented in a calendar format then.

**Comment by stephenreid321** [comment]
Already exists - see the iCal icon bottom right http://dandelion.events/o/the-psychedelic-society

![image](https://github.com/dandelion-collective/dandelion/assets/25448/41643499-9e9d-4cac-a02e-b085ac2cd5b1)

**Comment by samuk** [comment]
Ah great, thanks. I'm not seeing it on the page linked above? Is it only displayed for your own organisation?

If the ICS exists somewhere I could import that into something that provided a month view. I don't think there is one provided by default?

**Comment by stephenreid321** [comment]
Apologies, link should have been https://dandelion.events/o/the-psychedelic-society/events?search=1

> If the ICS exists somewhere I could import that into something that provided a month view. I don't think there is one provided by default?

As in, you would appreciate a month view on the site?

**Comment by samuk** [comment]
Yes, but I'm not an actual user yet, just evaluating it at the moment. It has some great features.  Nice work!

Are there any docs on how to install it anywhere? A Dockerised version would be ideal, but some docs would also really help.

My actual use case  for the month view would to be embedding different categories of events within my org on different websites, so I'd be interested in a minimal/ iframe optimised month view with some filters.

In the short term I could probably work around that by importing the ical into something that already provides that view.

Thanks

Sam

**Comment by stephenreid321** [comment]
added to https://dandelion.nolt.io/
