### ISSUE TITLE
Local group creation resulted in an error

### ISSUE THREAD

**Issue by samuk** [dandelion-collective/dandelion#34]
https://dandelion.events/local_groups/653fbfd3e7e7e90002ac8f62

![local-group-error](https://github.com/dandelion-collective/dandelion/assets/400875/169d5787-25a6-4193-80fc-5d992f52d1ab)

That's all I know. I added a polyon as suggested in the doce

**Comment by stephenreid321** [comment]
Looks like you added a line (LineString), not a Polygon.

Expected input is something like

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "coordinates": [
          [
            [
              -0.45326237723753593,
              51.75862087966547
            ],
            [
              -0.9189965413974619,
              51.13134208663297
            ],
            [
              0.42689625503106754,
              51.388214111664524
            ],
            [
              -0.45326237723753593,
              51.75862087966547
            ]
          ]
        ],
        "type": "Polygon"
      }
    }
  ]
}

**Comment by samuk** [comment]
OK thanks, our local groups are not always geographically specific, so I think I'm inclined to not use this functionality and just create a seperate org for each sub-circle/ group.

**Comment by stephenreid321** [comment]
Sounds like you're looking for Activities. These are non-geographical subgroups of an org.
