### ISSUE TITLE
'Secret event' disappeared

### ISSUE THREAD

**Issue by samuk** [dandelion-collective/dandelion#35]
I created an event called 'test2' (from memory) 

I 'purchased' two free tickets for it. I recieved the email confirmation. (see screenshot)

![Test2](https://github.com/dandelion-collective/dandelion/assets/400875/a9c6f441-9fb8-4131-8c9c-bf07c6532cf4)

But now that event has completely disappeared from my org

![test-org](https://github.com/dandelion-collective/dandelion/assets/400875/39368d9c-6db1-471e-af05-67bc1eda57ea)

Any idea where it went? Or am I just missing something in the UI?

**Comment by samuk** [comment]
Ah it does still exist https://dandelion.events/e/c3u87

**Comment by samuk** [comment]
I think this is just me getting familar with the UI.

There may be a bit of UX learning here, but closing the issue

**Comment by stephenreid321** [comment]
You will see it in the Event stats page at https://dandelion.events/o/test-org1/events/stats?from=2023-10-01
