### ISSUE TITLE
ical by tag, or tag included in ical

### ISSUE THREAD

**Issue by samuk** [dandelion-collective/dandelion#36]
I'd want to be able to present  events with a given tag on different websites/ calendars. So I'd need to be able to either:

1) Get a iCal of all my organisations events with a given 'tag'

2) Or alternately have a single iCAL with the event tags given as part of the information provided in the iCal

Does either of those exist already? I'm having problems viewing my tagged events.

**Comment by samuk** [comment]
I guess I could also set up different orgs for each 'type' of event. That might work.

**Comment by stephenreid321** [comment]
If you do a search before copying the link to the ICS feed it will retain search options, e.g. https://dandelion.events/o/the-psychedelic-society/events.ics?display=&order=&minimal=&from=2023-11-01&q=&event_tag_id=64903d2b1bbf5c00029cc726&local_group_id=&activity_id=&search=1 will be an ICS feed of The Psychedelic Society's events tagged 'artificial intelligence'

**Comment by samuk** [comment]
Nice, thanks
